#Requires -Version 7.0
#Requires -Modules @{ ModuleName="Az.Accounts"; ModuleVersion="2.0.0" }
#Requires -Modules @{ ModuleName="Az.Resources"; ModuleVersion="6.0.0" }

<#
.SYNOPSIS
    Creates and configures an Entra ID (Azure AD) App Registration for Azure Static Web App authentication.

.DESCRIPTION
    This script automates the creation of an Entra ID App Registration with the required
    configuration for authenticating users to an Azure Static Web App. It sets up:
    - App Registration with appropriate redirect URIs
    - Required API permissions (Microsoft Graph)
    - Client credentials (if needed)
    - Admin consent for permissions

.PARAMETER AppName
    The display name for the Entra ID App Registration (default: "Wiki Docs Static Web App")

.PARAMETER StaticWebAppHostname
    The hostname of the Azure Static Web App (e.g., "happy-sea-123456789.centralus.1.azurestaticapps.net")
    If not provided, the script will prompt for it after deployment.

.PARAMETER TenantId
    The Azure AD Tenant ID. If not provided, uses the current tenant from context.

.EXAMPLE
    .\setup-entra-app.ps1 -AppName "My Docs App" -StaticWebAppHostname "my-app.azurestaticapps.net"

.EXAMPLE
    .\setup-entra-app.ps1
    # Will use default name and prompt for hostname

.NOTES
    Prerequisites:
    - PowerShell 7.0 or higher
    - Az PowerShell modules (Az.Accounts, Az.Resources)
    - Appropriate permissions in Azure AD to create app registrations
    - Global Administrator or Application Administrator role recommended

    Author: Generated by Azure IaC Hub
    Version: 1.0.0
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$AppName = "Wiki Docs Static Web App",

    [Parameter(Mandatory = $false)]
    [string]$StaticWebAppHostname,

    [Parameter(Mandatory = $false)]
    [string]$TenantId
)

# ============================================================================
# Configuration
# ============================================================================

$ErrorActionPreference = "Stop"
$InformationPreference = "Continue"

# Required Microsoft Graph API permissions
$RequiredResourceAccess = @{
    ResourceAppId = "00000003-0000-0000-c000-000000000000" # Microsoft Graph
    ResourceAccess = @(
        @{
            Id = "e1fe6dd8-ba31-4d61-89e7-88639da4683d" # User.Read
            Type = "Scope"
        },
        @{
            Id = "64a6cdd6-aab1-4aaf-94b8-3cc8405e90d0" # email
            Type = "Scope"
        },
        @{
            Id = "14dad69e-099b-42c9-810b-d002981feec1" # profile
            Type = "Scope"
        },
        @{
            Id = "37f7f235-527c-4136-accd-4a02d197296e" # openid
            Type = "Scope"
        }
    )
}

# ============================================================================
# Functions
# ============================================================================

function Write-Step {
    param([string]$Message)
    Write-Information "`n========================================" -InformationAction Continue
    Write-Information "  $Message" -InformationAction Continue
    Write-Information "========================================`n" -InformationAction Continue
}

function Write-Success {
    param([string]$Message)
    Write-Host "✓ $Message" -ForegroundColor Green
}

function Write-WarningMessage {
    param([string]$Message)
    Write-Host "⚠ $Message" -ForegroundColor Yellow
}

function Write-ErrorMessage {
    param([string]$Message)
    Write-Host "✗ $Message" -ForegroundColor Red
}

function Test-Prerequisites {
    Write-Step "Checking Prerequisites"

    # Check PowerShell version
    if ($PSVersionTable.PSVersion.Major -lt 7) {
        Write-ErrorMessage "PowerShell 7.0 or higher is required. Current version: $($PSVersionTable.PSVersion)"
        exit 1
    }
    Write-Success "PowerShell version: $($PSVersionTable.PSVersion)"

    # Check Az modules
    $requiredModules = @("Az.Accounts", "Az.Resources")
    foreach ($module in $requiredModules) {
        if (-not (Get-Module -ListAvailable -Name $module)) {
            Write-ErrorMessage "Required module '$module' is not installed."
            Write-Information "Install it with: Install-Module -Name $module -Scope CurrentUser"
            exit 1
        }
        Write-Success "Module '$module' is available"
    }

    # Check Azure connection
    try {
        $context = Get-AzContext
        if (-not $context) {
            Write-Warning "Not connected to Azure. Please login..."
            Connect-AzAccount
            $context = Get-AzContext
        }
        Write-Success "Connected to Azure"
        Write-Information "  Tenant: $($context.Tenant.Id)"
        Write-Information "  Subscription: $($context.Subscription.Name) ($($context.Subscription.Id))"
        Write-Information "  Account: $($context.Account.Id)"

        return $context
    }
    catch {
        Write-ErrorMessage "Failed to connect to Azure: $_"
        exit 1
    }
}

function New-EntraAppRegistration {
    param(
        [string]$DisplayName,
        [string]$TenantId,
        [string[]]$RedirectUris
    )

    Write-Step "Creating Entra ID App Registration"

    try {
        # Create the app registration
        Write-Information "Creating app registration: $DisplayName"

        $appParams = @{
            DisplayName = $DisplayName
            SignInAudience = "AzureADMyOrg"
            Web = @{
                RedirectUris = $RedirectUris
                ImplicitGrantSettings = @{
                    EnableIdTokenIssuance = $true
                    EnableAccessTokenIssuance = $true
                }
            }
            RequiredResourceAccess = @($RequiredResourceAccess)
        }

        # Note: Using Az CLI for app registration as Az.Resources module has limited support
        $appJson = az ad app create `
            --display-name $DisplayName `
            --sign-in-audience "AzureADMyOrg" `
            --web-redirect-uris @RedirectUris `
            --enable-id-token-issuance true `
            --enable-access-token-issuance true `
            --required-resource-accesses (ConvertTo-Json -Depth 10 @($RequiredResourceAccess) -Compress) `
            2>&1

        if ($LASTEXITCODE -ne 0) {
            throw "Failed to create app registration: $appJson"
        }

        $app = $appJson | ConvertFrom-Json
        Write-Success "App registration created successfully"
        Write-Information "  App ID: $($app.appId)"
        Write-Information "  Object ID: $($app.id)"

        return $app
    }
    catch {
        Write-ErrorMessage "Failed to create app registration: $_"
        throw
    }
}

function Grant-AdminConsent {
    param(
        [string]$AppId,
        [string]$TenantId
    )

    Write-Step "Granting Admin Consent"

    try {
        Write-Information "Granting admin consent for API permissions..."
        Write-Warning "This requires Global Administrator or Privileged Role Administrator permissions"

        $result = az ad app permission admin-consent --id $AppId 2>&1

        if ($LASTEXITCODE -eq 0) {
            Write-Success "Admin consent granted successfully"
        }
        else {
            Write-Warning "Could not grant admin consent automatically"
            Write-Information "Please grant admin consent manually in the Azure Portal:"
            Write-Information "  https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/CallAnAPI/appId/$AppId"
        }
    }
    catch {
        Write-Warning "Failed to grant admin consent: $_"
        Write-Information "Please grant it manually in the Azure Portal"
    }
}

function Export-Configuration {
    param(
        [object]$App,
        [string]$TenantId,
        [string]$Hostname
    )

    Write-Step "Configuration Summary"

    $config = @{
        AppName = $App.displayName
        ClientId = $App.appId
        TenantId = $TenantId
        ObjectId = $App.id
        RedirectUris = $App.web.redirectUris
        StaticWebAppHostname = $Hostname
    }

    Write-Information "Entra ID App Registration Configuration:"
    Write-Information "=========================================="
    Write-Information "App Name:     $($config.AppName)"
    Write-Information "Client ID:    $($config.ClientId)"
    Write-Information "Tenant ID:    $($config.TenantId)"
    Write-Information "Object ID:    $($config.ObjectId)"
    Write-Information ""
    Write-Information "Redirect URIs:"
    foreach ($uri in $config.RedirectUris) {
        Write-Information "  - $uri"
    }
    Write-Information ""

    # Export to file
    $outputFile = Join-Path $PSScriptRoot "entra-app-config.json"
    $config | ConvertTo-Json -Depth 10 | Out-File -FilePath $outputFile -Encoding utf8
    Write-Success "Configuration exported to: $outputFile"

    Write-Information "`nNext Steps:"
    Write-Information "==========="
    Write-Information "1. Store the Client ID as a GitHub secret or variable:"
    Write-Information "   ENTRA_CLIENT_ID=$($config.ClientId)"
    Write-Information ""
    Write-Information "2. Store the Tenant ID as a GitHub secret or variable:"
    Write-Information "   ENTRA_TENANT_ID=$($config.TenantId)"
    Write-Information ""
    Write-Information "3. Update infrastructure/parameters.json with these values"
    Write-Information ""
    Write-Information "4. Deploy the infrastructure using Bicep:"
    Write-Information "   az deployment group create \"
    Write-Information "     --resource-group <your-rg-name> \"
    Write-Information "     --template-file infrastructure/main.bicep \"
    Write-Information "     --parameters infrastructure/parameters.json \"
    Write-Information "     --parameters entraClientId='$($config.ClientId)' \"
    Write-Information "     --parameters entraTenantId='$($config.TenantId)'"
    Write-Information ""
    Write-Information "5. Configure GitHub environment variables in Static Web App:"
    Write-Information "   ENTRA_CLIENT_ID=$($config.ClientId)"
    Write-Information ""
    Write-Information "6. Grant admin consent if not already done:"
    Write-Information "   https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/CallAnAPI/appId/$($config.ClientId)"
}

# ============================================================================
# Main Script
# ============================================================================

try {
    Write-Information "═══════════════════════════════════════════════════════════"
    Write-Information "  Entra ID App Registration Setup"
    Write-Information "  For Azure Static Web App Authentication"
    Write-Information "═══════════════════════════════════════════════════════════"

    # Check prerequisites and get Azure context
    $context = Test-Prerequisites

    # Get or set tenant ID
    if (-not $TenantId) {
        $TenantId = $context.Tenant.Id
    }

    # Get Static Web App hostname if not provided
    if (-not $StaticWebAppHostname) {
        Write-Information "`nNOTE: You can run this script before deploying the Static Web App."
        Write-Information "      You'll need to update the redirect URIs after deployment.`n"

        $response = Read-Host "Do you have the Static Web App hostname? (y/n)"
        if ($response -eq 'y') {
            $StaticWebAppHostname = Read-Host "Enter the Static Web App hostname (e.g., happy-sea-123.1.azurestaticapps.net)"
        }
        else {
            Write-Warning "Redirect URIs will need to be updated after Static Web App deployment"
            $StaticWebAppHostname = "placeholder.azurestaticapps.net"
        }
    }

    # Build redirect URIs
    $redirectUris = @(
        "https://$StaticWebAppHostname/.auth/login/aad/callback"
    )

    # Create the app registration
    $app = New-EntraAppRegistration -DisplayName $AppName -TenantId $TenantId -RedirectUris $redirectUris

    # Grant admin consent
    Grant-AdminConsent -AppId $app.appId -TenantId $TenantId

    # Export configuration
    Export-Configuration -App $app -TenantId $TenantId -Hostname $StaticWebAppHostname

    Write-Information ""
    Write-Success "Setup completed successfully!"
    Write-Information ""
}
catch {
    Write-ErrorMessage "Script failed: $_"
    Write-Information $_.ScriptStackTrace
    exit 1
}
